[note]
filename = "{{format-date now '%Y%m%d%H%M%S'}}-{{slug title}}"
extension = "md"
template = "default.md"

[tool]
editor = "nvim"

[lsp.diagnostics]
dead-link = "warning"

[group.daily]
paths = ["daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
template = "daily.md"

[group.inbox]
paths = ["inbox"]

[group.inbox.note]
filename = "{{format-date now '%Y%m%d%H%M%S'}}-{{slug title}}"
template = "default.md"

[group.projects]
paths = ["projects"]

[group.projects.note]
filename = "{{slug title}}"
template = "project.md"

[group.areas]
paths = ["areas"]

[group.areas.note]
filename = "{{slug title}}"
template = "area.md"

[group.resources]
paths = ["resources"]

[group.resources.note]
filename = "{{slug title}}"
template = "default.md"

[group.people]
paths = ["people"]

[group.people.note]
filename = "{{slug title}}"
template = "person.md"

[group.ideas]
paths = ["ideas"]

[group.ideas.note]
filename = "{{format-date now '%Y%m%d%H%M%S'}}-{{slug title}}"
template = "idea.md"

[group.learning]
paths = ["learning"]

[group.learning.note]
filename = "{{slug title}}"
template = "learning.md"

[alias]
daily   = 'zk new --no-input "$ZK_NOTEBOOK_DIR/daily"'
inbox   = 'zk new --title "$*" "$ZK_NOTEBOOK_DIR/inbox"'
person  = 'zk new --title "$*" "$ZK_NOTEBOOK_DIR/people"'
project = 'zk new --title "$*" "$ZK_NOTEBOOK_DIR/projects"'
idea    = 'zk new --title "$*" "$ZK_NOTEBOOK_DIR/ideas"'
learn   = 'zk new --title "$*" "$ZK_NOTEBOOK_DIR/learning"'
recent  = "zk list --sort modified- --limit 20"
broken  = "zk list --link-broken"
